### ISSUE TITLE
Error setting up entry for miner

### ISSUE THREAD

**Issue by JurreA02** [Schnitzel/hass-miner#166]
When adding integration miner it gives me the below error. Using latest HA OS and latest hass-miner (main).

2023-05-12 10:47:51.707 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry s9j-heater for miner
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/miner/__init__.py", line 24, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by petrsychrava** [comment]
Changing line 24 in custom_components/miner/__init__.py to 
`await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)`
fixes the problem

**Comment by UpstreamData** [comment]
This is fixed as part of #39, just making sure it's good to go then it will get merged.
