### ISSUE TITLE
Error during setup of AntminerS9

### ISSUE THREAD

**Issue by Buster2k6** [Schnitzel/hass-miner#205]
Hi, I installed version 0.6.0 of Miner in Home Assistant and now I'm trying to integrate my Antminer S9 with Braiins OS+ there. I can access it via the web interface and control it from there. Password is not set. 
If I want to add it in the integration, it works, the IP is accepted and the miner name is automatically filled in, but then comes with the error message. 
No devices or entities. Error setting up.

Error setting up entry miner-98f751 for miner
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/miner/__init__.py", line 24, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'.

anyone an idea ?

**Comment by Buster2k6** [comment]
ok, now that i have installed beta 1.0 i was able to add the miner successfully, however i only have one entity, only on and off, that is a bit disappointing.

**Comment by Buster2k6** [comment]
ok, after a few minutes the other entities came too, so everything works now.
