### ISSUE TITLE
Unable to Add T17+ running Braiins

### ISSUE THREAD

**Issue by schwoi** [Schnitzel/hass-miner#301]
## Version of the custom_component
Miner:
V1.1.0

Home Assistant
Core 2024.1.5
Supervisor 2023.12.1
Operating System 11.4
Frontend 20240104.0

Braiins:
Version: 2022-06-20-0-288861e4-22.05-plus

## Describe the bug

After Upgrading to the latest version I am unable to add the Antminer T17+ running Braiins.
I was able to add an S9 and an S19 without issue.

![image](https://github.com/Schnitzel/hass-miner/assets/7381086/29a1250f-f2dd-498b-b0ac-b666ec1a1985)

## Debug log

```text

2024-01-25 11:06:03.297 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 233, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 320, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 416, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/miner/config_flow.py", line 150, in async_step_login
    return await self.async_step_title()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/miner/config_flow.py", line 154, in async_step_title
    title = await self._miner.get_hostname()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyasic/miners/base.py", line 288, in get_hostname
    return await self._get_hostname()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyasic/miners/backends/braiins_os.py", line 766, in _get_hostname
    grpc_miner_details = await self.web.grpc.get_miner_details()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyasic/web/braiins_os/grpc.py", line 400, in get_miner_details
    return await self.send_command("get_miner_details", GetMinerDetailsRequest())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyasic/web/braiins_os/grpc.py", line 95, in send_command
    metadata.append(("authorization", await self.auth()))
                                      ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyasic/web/braiins_os/grpc.py", line 119, in auth
    await self._get_auth()
  File "/usr/local/lib/python3.11/site-packages/pyasic/web/braiins_os/grpc.py", line 131, in _get_auth
    await stream.send_message(req, end=True)
  File "/usr/local/lib/python3.11/site-packages/grpclib/client.py", line 241, in send_message
    await self.send_request()
  File "/usr/local/lib/python3.11/site-packages/grpclib/client.py", line 173, in send_request
    protocol = await self._channel.__connect__()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/grpclib/client.py", line 748, in __connect__
    self._protocol = await self._create_connection()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/grpclib/client.py", line 725, in _create_connection
    _, protocol = await self._loop.create_connection(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 628, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 668, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.36.43', 50051)

```

**Comment by UpstreamData** [comment]
You need to update the S17 to the most recent possible version for it to work properly.  pyasic is too lazy to track what versions have what features, or even check what version a miner is unless you ask for it, so it just assumes that S17s and S19s have both been updated enough to use gRPC.

**Comment by Chris-S44** [comment]
I have this same error on a T17 that is on the latest braiins 2023-01
I cannot add it. It was working before updating home assistant and miner.

**Comment by b-rowan** [comment]
> I have this same error on a T17 that is on the latest braiins 2023-01 I cannot add it. It was working before updating home assistant and miner.

Can you send logs from setup?

**Comment by schwoi** [comment]
> You need to update the S17 to the most recent possible version for it to work properly. pyasic is too lazy to track what versions have what features, or even check what version a miner is unless you ask for it, so it just assumes that S17s and S19s have both been updated enough to use gRPC.

Silly me, should have throught to check the version. Just assumed it kept itself upto date.
Now running Version: 2024-01-15-0-e8253ec1-23.12.1-plus works for me.

**Comment by Chris-S44** [comment]
> > You need to update the S17 to the most recent possible version for it to work properly. pyasic is too lazy to track what versions have what features, or even check what version a miner is unless you ask for it, so it just assumes that S17s and S19s have both been updated enough to use gRPC.
> 
> Silly me, should have throught to check the version. Just assumed it kept itself upto date. Now running Version: 2024-01-15-0-e8253ec1-23.12.1-plus works for me.

Where did you find that version of braiins? Their latest for T17+ is 23.01

**Comment by b-rowan** [comment]
Try https://feeds.braiins-os.com

**Comment by Chris-S44** [comment]
> Try https://feeds.braiins-os.com

Braiins support say not to update T17 past 23.01
![Screenshot_20240126_071846](https://github.com/Schnitzel/hass-miner/assets/90959458/b72c52c8-1c79-4c33-9cbc-232883d7a7fe)

**Comment by schwoi** [comment]
I ran the update via the braiins toolbox.
Interesting about the don't update past.

**Comment by b-rowan** [comment]
I've reached out to some people on support directly, he's asking the support group, we'll get an answer here shortly.  Not sure why they wouldn't want you to update, but if toolbox is letting you then I don't see an issue.

**Comment by Chris-S44** [comment]
> I've reached out to some people on support directly, he's asking the support group, we'll get an answer here shortly. Not sure why they wouldn't want you to update, but if toolbox is letting you then I don't see an issue.

Apparently anything past 23.01 on the x17 models the auto tune never finishes

**Comment by b-rowan** [comment]
Genius.  I'm going to do some complaining directly to the devs, maybe eventually this fix this.

**Comment by schwoi** [comment]
Sweet, I must have just got lucky.
![image](https://github.com/Schnitzel/hass-miner/assets/7381086/de280452-bae4-4fd5-97c9-36a01143fdee)
Thanks for the heads up though @Chris-S44

**Comment by monkeyjpg** [comment]
I can see the same issue on my HA instance. I could not solve it so removed haas-miner and added again , started fresh. Still the same situation. I cannot add miner.

![scrmn](https://github.com/Schnitzel/hass-miner/assets/126238084/3ed056d1-0871-4e2a-ae7a-9fe1a32536a4)


--------------
Antminer S19J Pro NoPic 
Braiins OS+	2024-01-15-0-e8253ec1-23.12.1-plus (latest version)

--------------
Home Assistant

Core 2024.1.5
Supervisor 2023.12.1
Operating System 11.4

hass-miner 1.1.1

--------------
Logger: aiohttp.server
Source: /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py:421

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 233, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 320, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 416, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/miner/config_flow.py", line 150, in async_step_login
    return await self.async_step_title()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/miner/config_flow.py", line 154, in async_step_title
    title = await self._miner.get_hostname()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyasic/miners/base.py", line 288, in get_hostname
    return await self._get_hostname()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyasic/miners/backends/braiins_os.py", line 766, in _get_hostname
    grpc_miner_details = await self.web.grpc.get_miner_details()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyasic/web/braiins_os/grpc.py", line 400, in get_miner_details
    return await self.send_command("get_miner_details", GetMinerDetailsRequest())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyasic/web/braiins_os/grpc.py", line 95, in send_command
    metadata.append(("authorization", await self.auth()))
                                      ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyasic/web/braiins_os/grpc.py", line 119, in auth
    await self._get_auth()
  File "/usr/local/lib/python3.11/site-packages/pyasic/web/braiins_os/grpc.py", line 132, in _get_auth
    await stream.recv_initial_metadata()
  File "/usr/local/lib/python3.11/site-packages/grpclib/client.py", line 393, in recv_initial_metadata
    self._raise_for_grpc_status(status, message, details)
  File "/usr/local/lib/python3.11/site-packages/grpclib/client.py", line 345, in _raise_for_grpc_status
    raise GRPCError(status, message, details)
grpclib.exceptions.GRPCError: (<Status.UNAUTHENTICATED: 16>, 'Bad credentials', None)

**Comment by b-rowan** [comment]
This should really be a separate issue, what you're talking about is completely unrelated.  It's a credential issue with gRPC, vs not having gRPC at all on different miners.

Regarding the actual issue, try to default password?  I have no idea how the gRPC instance syncs passwords with the main API, so it's very possible it hasn't been changed.

**Comment by dcod3d** [comment]
Also on 23.01 for my S17s. Rolled back to 1.1.0-beta for the time being.

**Comment by dcod3d** [comment]
Looks like it's fixed in the latest version of pyasic to work with X17s on braiins 23.01

https://github.com/UpstreamData/pyasic/issues/104
