### ISSUE TITLE
Einrichtungsfehler S9 HA

### ISSUE THREAD

**Issue by bolek1** [Schnitzel/hass-miner#436]
HA Core 2024.11.3 (green)
Miner: 1.1.19rc3
S9 mit Braiins Version: 2022-09-27-0-26ba61b9-22.08.1-plus

![image](https://github.com/user-attachments/assets/34a0c99f-3e1e-4c17-b3bf-849fd4797715)

Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: custom_components.miner.coordinator
Quelle: custom_components/miner/coordinator.py:91
Integration: Miner (Dokumentation, Probleme)
Erstmals aufgetreten: 18:38:57 (4 Vorkommnisse)
Zuletzt protokolliert: 18:39:50

LUCI web command failed: command=bos/info, code=401
Traceback (most recent call last):
  File "/config/custom_components/miner/coordinator.py", line 91, in _async_update_data
    miner_data = await self.miner.get_data(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyasic/miners/base.py", line 535, in get_data
    gathered_data = await self._get_data(
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyasic/miners/base.py", line 460, in _get_data
    await asyncio.gather(rpc_command_task, web_command_task)
  File "/usr/local/lib/python3.12/site-packages/pyasic/web/braiins_os/bosminer.py", line 67, in multicommand
    data[command] = await self.send_command(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyasic/web/braiins_os/bosminer.py", line 54, in send_command
    raise APIError(
pyasic.errors.APIError: LUCI web command failed: command=bos/info, code=401

**Comment by b-rowan** [comment]
Did you set the web password for this miner correctly?  S9s running BOS need a web password and an SSH password set if you have them updated in the firmware, usually the default for most miners (`root`/`root`) will work.  You can also try with no password for both.

**Comment by bolek1** [comment]
that's it. i changed the password for the web interface of the S9 and didn't think about it anymore. thanks
